### ISSUE TITLE
White borders around messages

### ISSUE THREAD

**Issue by dtasev** [auscompgeek/fb-messenger-dark#16]
Hey, seems FB just pushed an update that makes some changes to the chat bubbles, a fix for the white borders just to add border color for own and other messages:

```
/* message */
._29_7 ._hh7, ._29_7._-5k ._hh7 {
	background-color: #2d2d30;
    border-color:#414141;
}
/* own message */
._o46._nd_ ._hh7 {
	background-color: #004488;
    border-color:#000000;
}
```

The color for the border for each message could be changed, the own one is pure black, while the other one is dark gray, but slightly lighter than the background. I am not sure how it was before, but I think it looks nice!

**Comment by auscompgeek** [comment]
Ugh. This is causing rendering artifacts on the curved corners on the bubbles. Why did Facebook think this was a good idea.

I do agree that a subtle border on incoming messages looks nice, although a black border around outgoing messages is unnoticeable to me. Hm.

I'm in class right now, so I might push out a fix later this evening.
