### ISSUE TITLE
Ubuntu 12.04 LTS: Text-enter box remains white

### ISSUE THREAD

**Issue by pyronamic** [auscompgeek/fb-messenger-dark#2]
See attached image. 

![screenshot from 2016-01-26 17 58 46](https://cloud.githubusercontent.com/assets/16908368/12598944/96a96df0-c45b-11e5-80eb-af0258fff354.png)

Error started happening after the most recent (Jan 26th) update

**Comment by ayylmaoxx** [comment]
Likewise on Safari Version 9.0.1 (10601.2.7.2) on Mac OS 10.10.4
I can't see the blinking text cursor or the text I'm typing.

**Comment by lawrenceadams** [comment]
Same here on Google Chrome 47.0.2526.111

**Comment by dpzmick** [comment]
Can confirm. on 14.10.

**Comment by auscompgeek** [comment]
Fixed in 5cd71e7508.

[Corresponding userstyles.org thread](https://forum.userstyles.org/discussion/48574/x).
