### ISSUE TITLE
Bar below chat box

### ISSUE THREAD

**Issue by haydster7** [auscompgeek/fb-messenger-dark#20]
I dont know how to use git properly

you need to add this code to the css

._4_j4 .chatAttachmentShelf {
	border-top: none;
}

I'd love to be a contributor, just don't know how to add stuff.

**Comment by auscompgeek** [comment]
Heh, thanks. I was wondering whether I was the only one seeing this.

This isn't the full story though. That element also gives you link attachment previews when composing a message. Check it out by typing a link into the composer.

I've been a bit busy the past couple of days, but I'll see if I have a chance to fix this up tomorrow afternoon.

**Comment by haydster7** [comment]
Ahh, I see. I've put a comment on userstyles as well, just ignore that.

**Comment by auscompgeek** [comment]
Heh, fun. userstyles.org's forums are rather annoying since there doesn't seem to be a way to get email notifications for new reviews. Luckily I get GitHub notifications left, right, and centre, so if there are any major issues with this, the internet lets me know rather quickly.

**Comment by auscompgeek** [comment]
Fixed in beb979ecfa31. Sorry it took so long, I got caught up in other things today.

**Comment by haydster7** [comment]
Legend 👍
