### ISSUE TITLE
Top bar lost it's shade of gray

### ISSUE THREAD

**Issue by macfeaster** [auscompgeek/fb-messenger-dark#22]
Great theme, great updates as always!

One thing has been bugging me a bit lately, I think Facebook changed some class names or something, because the theme kind of broke a bit.

The top bar used to be lighter, framing the chat content nicely, but now it has the same background as the chat content, leaving only the right panel with the lighter color.

How the screenshot in the README looks, and how the theme looked until ~1 mo ago:
<img width="731" alt="screen shot 2018-03-15 at 10 44 11 pm" src="https://user-images.githubusercontent.com/6403471/37470445-82f05870-28a2-11e8-8ddd-4ce493c54ca0.png">

How the theme currently looks on messenger.com:
<img width="733" alt="screen shot 2018-03-15 at 10 43 50 pm" src="https://user-images.githubusercontent.com/6403471/37470471-8ed705c6-28a2-11e8-8565-f4cfd8b831ff.png">

Hopefully easily fixed!

**Comment by auscompgeek** [comment]
Hey, thanks for the bug report.

This has been bugging me a bit too, but now it's seriously bugging me even more, as now the chat list header is the grey it used to be, but the conversation header isn't…

Unfortunately I haven't had a chance to look into fixing this, but it should be easily fixed.

**Comment by auscompgeek** [comment]
Fixed by #23.
