### ISSUE TITLE
White background behind "composing" bubble

### ISSUE THREAD

**Issue by macfeaster** [auscompgeek/fb-messenger-dark#25]
It's that time of the year again when Facebook arbitrarily changes class names and styling to break this otherwise impeccable theme :nerd_face: 

The background behind the three-dots-in-a-bubble has turned white since a few weeks.

![c8a730509f9a650397ac8d7ea4dc00b1](https://user-images.githubusercontent.com/6403471/47270955-5fcc9b00-d573-11e8-9951-871396ba851c.png)

I've been using this hotfix which seems to work well:

```css
._4gd0 {
  background: transparent !important;
}
```

**Comment by auscompgeek** [comment]
Weird... I've actually been using this for the past week and hadn't noticed this. I'll, uhh, I guess fix this along with all the other bugs I've noticed in the past couple of months at some point.

**Comment by auscompgeek** [comment]
Yeah, I actually can't seem to reproduce this.

**Comment by macfeaster** [comment]
Probably part of some staged rollout, it's really just the single element with the above classname that has white background.
