### ISSUE TITLE
Messenger header text is dark

### ISSUE THREAD

**Issue by mogzol** [auscompgeek/fb-messenger-dark#26]
The "Messenger" header in the top corner's color is not being changed to white. This seems to be because it is an `h1` which is not covered by this userstyle. Adding `h1` to the rule with the other headers fixes the issue:

```
h1, h2, h3, h4, h5, h6
{
    color: #eee;
}
```

Here is a screenshot showing the problem I am talking about:
![image](https://user-images.githubusercontent.com/11789801/48285657-27a0d580-e418-11e8-9470-27e1fc86b82d.png)

**Comment by auscompgeek** [comment]
Funny how long this bug has been sitting here. I just never got around to looking into it.
