### ISSUE TITLE
Remove background color for emoji-only messages

### ISSUE THREAD

**Issue by b-ggs** [auscompgeek/fb-messenger-dark#5]
Facebook Messenger finally updated how emoji-only messages appear on the web app.

Just like on the Messenger mobile app, emoji-only messages should not be in chat bubbles.

![foo2](https://cloud.githubusercontent.com/assets/6130147/12865899/b6644140-ccf5-11e5-8da2-ea8d6e540551.jpg)

**Comment by auscompgeek** [comment]
Oh, _finally_. I'll look into this today.

**Comment by auscompgeek** [comment]
Will push an update to userstyles.org soon (assuming it loads).

**Edit**: Update pushed out. Enjoy!
