### ISSUE TITLE
Highlight selected users in searchbar

### ISSUE THREAD

**Issue by janhieber** [auscompgeek/fb-messenger-dark#6]
Desc: In searchbar pressing button up/down to select users, they should be highlighted. Otherwise one can not see who is selected.

Reproduce: Click in searchbar top left, click kb buttons up/down.

Fix:

```
._1k1p {
    background-color: rgba(255, 255, 255, .4) !important;
}
```

**Comment by auscompgeek** [comment]
Ooh, I was unaware that keyboard selection was possible in search.

**Comment by auscompgeek** [comment]
I've decided to use `#1e1e1e` instead of the lighter grey suggested. If you feel that there's not enough contrast, please say so and feel free to make suggestions for alternative colours :smile:
